### ISSUE TITLE
tx-translator - i18nTextCollectorTask seems like it's being run in the wrong place

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-tx-translator#11]
The i18nTextCollectorTask, called via `$this->collectStrings()` in tx-translator, to the best of my knowledge:
- will scan PHP and JS files looking for NEW source (en.yml) strings that get TX_PUSH'ed to transifex
- It has nothing to do with translations strings that are TX_PULL'ed from transifex

However it looks like we call `$this->collectStrings()` in the wrong block - currently (this was copied from cow) the call resides in the TX_PULL block `if ($this->doTransifexPullAndUpdate) {` , rather than the TX_PUSH block `if ($this->doTransifexPush) {`.  It seems like it should be moved to the TX_PUSH block

### ACs
- [x] Confirm the assumptions above
- [x] Move the call to the TX_PUSH block

### PRs
- https://github.com/silverstripe/silverstripe-tx-translator/pull/12

**Comment by GuySartorelli** [comment]
PR merged. CLosing.
