### ISSUE TITLE
English appearing in translation files

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-tx-translator#23]
A few PRs from the run 4.13 run on the latest [translation issue](https://github.com/silverstripe/.github/issues/153) have English in the translation files

- https://github.com/silverstripe/silverstripe-mfa/pull/518
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1417
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/162

Work out why english is appearing and fix the bug

## PRs
- https://github.com/silverstripe/silverstripe-tx-translator/pull/24
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1420
- https://github.com/silverstripe/silverstripe-mfa/pull/520
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/164
- https://github.com/colymba/GridFieldBulkEditingTools/pull/258

**Comment by GuySartorelli** [comment]
All PRs merged
